# CircleCI 2.1 を使用
version: 2.1
# 公開されているCircleCI設定を読み込む。version: 2.1以上
orbs:  
  ruby: circleci/ruby@2.0.0 

jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.2
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler:2.3.7
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install